const projectList = [
  {
    title: "ALD Equipment",
    links: "/ALD",
    company: "KITECH",
    year: "2020",
    background: "https://i.imgur.com/QL6Rhs7.png",
    tag: "Engineering",
    details:
      "Prototype of the equipment to perform the ALD process of 100mm Wafer. Maintaining the degree of vacuum in the rotating chamber was the key point. Eventually, magnetic fluid was used to solve it, but there are many limitations and a new type of equipment is being developed.",
    titleColor: "Black",
    role: "Design Engineering, Manufacturing, S/W Product Design",
    goal: "Improve communication function",
  },
  {
    title: "볶다 · Bokdda",
    links: "/Bokdda",
    company: "Personal Project",
    year: "2021",
    background: "https://i.imgur.com/QPNqqhO.png",
    tag: "UI/UX",
    details:
      "Hydrogen compressor development project that does not require additional sealing by applying a magnet type rodless cylinder.",
    titleColor: "white",
    role: "Product Design, MVP develop",
    goal: "복지 검색과 신청의 간편함.",
  },
  {
    title: "OLED Equipment",
    links: "/OLED",
    company: "TNG",
    year: "2020",
    background: "https://i.imgur.com/f71RFmr.png",
    tag: "Engineering",
    details:
      "This equipment is used to safely transport OLED materials. We considered compatibility with existing equipment and operator's safety",
    titleColor: "Black",
    role: "Design Engineering",
    goal: "Protect operator, Increase usability",
  },
  {
    title: "Javara-light",
    links: "/JavaraLight",
    company: "BE THE LIGHT",
    year: "2021",
    background: "https://i.imgur.com/8fQdX3T.png",
    tag: "Design",
    details: "",
    titleColor: "Black",
    role: "Design",
    goal: "Lights for kids",
  },
  {
    title: "Hydrogen compressor",
    links: "/Hydrogen",
    company: "TNG",
    year: "2021",
    background: "",
    tag: "Design Engineering",
    details:
      "Hydrogen compressor development project that does not require additional sealing by applying a magnet type rodless cylinder.",
    titleColor: "Black",
  },
  {
    title: "Padintosh",
    links: "/Padintosh",
    company: "Personal Project",
    year: "2020",
    background: "https://i.imgur.com/CtdBJAc.png",
    tag: "Design",
    details: "Retro iPad Stand.",
    titleColor: "White",
    role: "Design Engineering, Web Develop",
    goal: "Back to the old days :)",
  },
  {
    title: "Fire Alarm",
    links: "/FireAlarm",
    company: "Gaon Tech",
    year: "2020",
    background: "https://i.imgur.com/nTfTpzD.png",
    tag: "Design",
    details:
      "Fire alarm provided with a fire extinguisher. We produced two types, a press process to bend the steel plate and mass production through an injection mold.",
    titleColor: "Black",
    role: "Design Engineering",
    goal: "Improve communication function",
  },
  {
    title: "Toothbrush",
    links: "/Toothbrush",
    company: "Personal Project",
    year: "2020",
    background: "https://i.imgur.com/jtzychE.png",
    tag: "Design",
    details:
      "Toothbrush can be used as a module type. We made it compatible with ready-made toothbrush holders.",
    titleColor: "White",
    role: "Design Engineering",
    goal: "Replaceable toothbrush",
  },
  {
    title: "Liquid hydrogen compressor",
    links: "/LiquidHydrogen",
    company: "KIMM",
    year: "2021",
    background: "",
    tag: "Engineering",
    details:
      "Hydrogen compressor development project that does not require additional sealing by applying a magnet type rodless cylinder.",
    titleColor: "Black",
  },
];

export default projectList;
