const projectList = [
  {
    key: 0,
    title: "ALD Equipment",
    links: "/ALD",
    company: "KITECH",
    year: "2020",
    background: "https://i.imgur.com/5zCniEb.png",
    tag: "Engineering",
    details:
      "In the ALD process wafer can't move to another space. Because wafers can be polluted by gas or particles. But if wafer can move to another space without pollution, process productivity will increase. So, our team developed this equipment prototype to prove our theory.",
    titleColor: "#0a0a0a",
    role: "#Design Engineering #Manufacturing #Product Design",
    goal:
      "- Wafer transporting in process - Rotating chamber - Vaccum sealing with magnetic fluid",
    category: "industrial",
  },
  {
    key: 1,
    title: "볶다",
    // links: "/Bokdda",
    company: "Personal Project",
    year: "2021",
    background: "https://i.imgur.com/QPNqqhO.png",
    tag: "UI/UX",
    details:
      "복지서비스 검색과 신청과정의 단순화를 위해 기획한 서비스 입니다. 총 6가지의 기준으로 복지를 분류하였고, 정부서비스와 연동하여 가족관계증명서, 주민등록등본 등 자주 쓰이는 서류를 생체인증 한번으로 제출할 수 있게끔 했습니다.",
    titleColor: "#fdfdfd",
    role: "#Product Design #MVP",
    goal: "복지 검색과 신청 개선",
    category: "digital",
    lock: true,
  },
  {
    key: 2,
    title: "OLED Equipment",
    links: "/OLED",
    company: "TNG",
    year: "2020",
    background: "https://i.imgur.com/f71RFmr.png",
    tag: "Engineering",
    details:
      "This equipment is used to safely transport OLED materials. We considered compatibility with existing equipment and operator's safety",
    titleColor: "#0a0a0a",
    role: "#Design Engineering",
    goal: "Protect operator, Increase usability",
    category: "industrial",
  },
  {
    key: 3,
    title: "Javara-light",
    // links: "/JavaraLight",
    company: "BE THE LIGHT",
    year: "2021",
    background: "https://i.imgur.com/8fQdX3T.png",
    tag: "Design",
    details: "",
    titleColor: "#0a0a0a",
    role: "#Industrial Design #Prototyping",
    goal: "Lights for kids",
    lock: true,
    cursor: "default",
    category: "industrial",
  },
  {
    key: 4,
    title: "Hydrogen compressor",
    // links: "/Hydrogen",
    company: "TNG",
    year: "2021",
    background: "https://i.imgur.com/FWmJjFY.png",
    tag: "Design Engineering",
    details:
      "Hydrogen compressor development project that does not require additional sealing by applying a magnet type rodless cylinder.",
    titleColor: "#fdfdfd",
    role: "#Design Engineering",
    category: "industrial",
    lock: true,
  },
  {
    key: 5,
    title: "Padintosh",
    links: "/Padintosh",
    company: "Personal Project",
    year: "2020",
    background: "https://i.imgur.com/CtdBJAc.png",
    tag: "Design",
    details: "Retro iPad Stand.",
    titleColor: "#fdfdfd",
    role: "#Design Engineering #Web Develop",
    goal: "Back to the old days :D",
    category: "industrial",
  },
  {
    key: 6,
    title: "Fire Alarm",
    links: "/FireAlarm",
    company: "Gaon Tech",
    year: "2020",
    background: "https://i.imgur.com/nTfTpzD.png",
    tag: "Design",
    details:
      "Fire alarm provided with a fire extinguisher. We produced two types, a press process to bend the steel plate and mass production through an injection mold.",
    titleColor: "#0a0a0a",
    role: "#Design Engineering",
    goal: "Improve communication function",
    category: "industrial",
  },
  {
    key: 7,
    title: "Toothbrush",
    links: "/Toothbrush",
    company: "Personal Project",
    year: "2020",
    background: "https://i.imgur.com/jtzychE.png",
    tag: "Design",
    details:
      "Toothbrush can be used as a module type. We made it compatible with ready-made toothbrush holders.",
    titleColor: "#fdfdfd",
    role: "#Design Engineering",
    goal: "Replaceable toothbrush",
    category: "industrial",
  },
  {
    key: 8,
    title: "Liquid hydrogen compressor",
    // links: "/LiquidHydrogen",
    company: "KIMM",
    year: "2021",
    background: "",
    tag: "Engineering",
    details:
      "Hydrogen compressor development project that does not require additional sealing by applying a magnet type rodless cylinder.",
    titleColor: "#0a0a0a",
    category: "industrial",
    lock: true,
  },
];

export default projectList;
